services:
  network-deploy-service:
    networks:
      - micro_network

  microservices-db-config:
    image: mysql:latest
    extends:
      service: network-deploy-service
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=root
      start_period: 10s
      interval: 10s
      timeout: 3s
      retries: 5

  microservices-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 750m

  microservices-configserver-config:
    extends:
      service: microservices-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_PROFILES_ACTIVE: default

  microservices-eurekaserver-config:
    extends:
      service: microservices-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
