spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:////Users//kushanxp//projects//microservices//configs"
        git:
          uri: https://github.com/kushanxp/udemy-microservices-configs.git
          default-label: main
          force-pull: true
          clone-on-start: true


encrypt:
  key: "K@#$KJKJ89798"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"